packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  "@types/node": ^24.0.3

  # UI & Styling
  "tailwind-merge": ^3.3.1
  "class-variance-authority": ^0.7.1
  "clsx": ^2.1.1

  # Three.js & Web GL
  "three": ^0.160.1
  "@types/three": ^0.152.1
  "@react-three/fiber": ^9.1.2
  "@react-three/drei": ^10.3.0

  # Misc
  zod: ^3.24.3

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

onlyBuiltDependencies:
  - esbuild
